/**
 * state.c
 *
 * Initial model-state loading and scattering for PAWSIM.
 *
 * Rank 0 reads AWSIM-format binary input files, then scatters owned tiles to
 * the Cartesian decomposition. Cell-centered fields have Nx x Ny global
 * extent. The Coriolis/vorticity input lives on the q grid, which carries an
 * extra east/north boundary line on wall domains.
 *
 */
#include "state.h"

/** Duplicate domain.c's block formula for rank-0 scatter metadata. */
static uint block_start_local (uint N, uint coord, uint dim)
{
  return (N*coord) / dim;
}

/** Number of global cells in a tile generated by block_start_local(). */
static uint block_size_local (uint N, uint coord, uint dim)
{
  return block_start_local(N,coord+1,dim) - block_start_local(N,coord,dim);
}

/** Copy a bounded string segment and always write a trailing NUL. */
static void copy_path_segment (char * dst, const char * src, size_t * pos)
{
  size_t len,avail;

  if ((dst == NULL) || (src == NULL) || (pos == NULL))
  {
    return;
  }
  if (*pos >= MAX_PARAMETER_FILENAME_LENGTH)
  {
    dst[MAX_PARAMETER_FILENAME_LENGTH-1] = '\0';
    return;
  }

  len = strlen(src);
  avail = MAX_PARAMETER_FILENAME_LENGTH - 1 - *pos;
  if (len > avail)
  {
    len = avail;
  }
  memcpy(dst+*pos,src,len);
  *pos += len;
  dst[*pos] = '\0';
}

/** Join an input directory and relative filename inside PAWSIM's path buffer. */
static void join_input_path (char * path, const char * dir, const char * name)
{
  size_t pos = 0;

  path[0] = '\0';
  copy_path_segment(path,dir,&pos);
  if ((pos > 0) && (path[pos-1] != '/'))
  {
    copy_path_segment(path,"/",&pos);
  }
  copy_path_segment(path,name,&pos);
}

/** Resolve an AWSIM file parameter relative to the input-file directory. */
static void resolve_input_path (const pawsim_config * cfg, const char * name, char * path)
{
  /** Input-file-relative paths are resolved in config.c and stored in inputDir. */
  if ((name == NULL) || (strlen(name) == 0))
  {
    path[0] = '\0';
    return;
  }

  if (name[0] == '/')
  {
    size_t pos = 0;

    path[0] = '\0';
    copy_path_segment(path,name,&pos);
  }
  else
  {
    join_input_path(path,cfg->inputDir,name);
  }
}

/** Fill owned cells with a scalar default before optional inputs are read. */
static void fill_field (pawsim_field2d * field, real value)
{
  uint i,j,g;

  g = field->nghost;
  for (i = 0; i < field->nx; i ++)
  {
    for (j = 0; j < field->ny; j ++)
    {
      field->a[i+g][j+g] = value;
    }
  }
}

/** Copy this rank's owned cell-centered tile from a rank-0 global matrix. */
static void copy_global_to_local (pawsim_field2d * field, real ** global,
                                  const pawsim_domain * dom)
{
  uint i,j,g;

  g = field->nghost;
  for (i = 0; i < field->nx; i ++)
  {
    for (j = 0; j < field->ny; j ++)
    {
      field->a[i+g][j+g] = global[dom->i0+i][dom->j0+j];
    }
  }
}

#ifdef PAWSIM_USE_MPI
/** Pack a cell-centered global tile for point-to-point startup scatter. */
static void pack_global_tile (real ** global, real * buf,
                              uint i0, uint j0, uint nx, uint ny)
{
  uint i,j,p = 0;

  for (i = 0; i < nx; i ++)
  {
    for (j = 0; j < ny; j ++)
    {
      buf[p++] = global[i0+i][j0+j];
    }
  }
}

/** Unpack a received cell-centered tile into owned local cells. */
static void unpack_local_tile (pawsim_field2d * field, real * buf)
{
  uint i,j,g,p = 0;

  g = field->nghost;
  for (i = 0; i < field->nx; i ++)
  {
    for (j = 0; j < field->ny; j ++)
    {
      field->a[i+g][j+g] = buf[p++];
    }
  }
}
#endif

/*
 * Scatter an AWSIM-format cell-centered matrix from rank 0 to all local tiles.
 * Halo cells are filled later by field.c once all owned cells are present.
 */
static bool scatter_global_field (pawsim_field2d * field, real ** global,
                                  const pawsim_domain * dom)
{
#ifdef PAWSIM_USE_MPI
  int rank;

  /** Simple scatter keeps startup logic readable while PAWSIM is still evolving. */
  if (dom->rank == 0)
  {
    copy_global_to_local(field,global,dom);

    for (rank = 1; rank < dom->size; rank ++)
    {
      int coords[2];
      uint i0,j0,nx,ny;
      real * buf = NULL;

      MPI_Cart_coords(dom->comm,rank,2,coords);
      i0 = block_start_local(dom->Nx,(uint) coords[0],(uint) dom->dims[0]);
      j0 = block_start_local(dom->Ny,(uint) coords[1],(uint) dom->dims[1]);
      nx = block_size_local(dom->Nx,(uint) coords[0],(uint) dom->dims[0]);
      ny = block_size_local(dom->Ny,(uint) coords[1],(uint) dom->dims[1]);
      buf = malloc((size_t) nx*ny*sizeof(real));
      if (buf == NULL)
      {
        return false;
      }
      pack_global_tile(global,buf,i0,j0,nx,ny);
      MPI_Send(buf,(int) (nx*ny),MPI_DOUBLE,rank,200,dom->comm);
      free(buf);
    }
  }
  else
  {
    real * buf = malloc((size_t) field->nx*field->ny*sizeof(real));
    if (buf == NULL)
    {
      return false;
    }
    MPI_Recv(buf,(int) (field->nx*field->ny),MPI_DOUBLE,0,200,dom->comm,MPI_STATUS_IGNORE);
    unpack_local_tile(field,buf);
    free(buf);
  }

  return true;
#else
  copy_global_to_local(field,global,dom);
  return true;
#endif
}

/** Extra q column owned by the east boundary rank on non-periodic x domains. */
static uint q_extra_x (const pawsim_domain * dom)
{
  /** Only the eastmost rank owns the extra q-grid column for an x wall. */
  return (!dom->periodic_x && (dom->i0+dom->nx == dom->Nx)) ? 1 : 0;
}

/** Extra q row owned by the north boundary rank on non-periodic y domains. */
static uint q_extra_y (const pawsim_domain * dom)
{
  /** Only the northmost rank owns the extra q-grid row for a y wall. */
  return (!dom->periodic_y && (dom->j0+dom->ny == dom->Ny)) ? 1 : 0;
}

/** Copy this rank's owned q-grid tile, including any physical boundary line. */
static void copy_global_q_to_local (pawsim_field2d * field, real ** global_q,
                                    const pawsim_domain * dom)
{
  uint i,j,g,qnx,qny;

  g = field->nghost;
  qnx = field->nx + q_extra_x(dom);
  qny = field->ny + q_extra_y(dom);

  for (i = 0; i < qnx; i ++)
  {
    for (j = 0; j < qny; j ++)
    {
      field->a[i+g][j+g] = global_q[dom->i0+i][dom->j0+j];
    }
  }
}

#ifdef PAWSIM_USE_MPI
/** Pack a q-grid tile for a rank, including east/north wall lines if owned. */
static void pack_global_q_tile (real ** global_q, real * buf,
                                uint i0, uint j0, uint qnx, uint qny)
{
  uint i,j,p = 0;

  for (i = 0; i < qnx; i ++)
  {
    for (j = 0; j < qny; j ++)
    {
      buf[p++] = global_q[i0+i][j0+j];
    }
  }
}

/** Unpack a rank-local q-grid tile into the local field storage. */
static void unpack_local_q_tile (pawsim_field2d * field, real * buf,
                                 uint qnx, uint qny)
{
  uint i,j,g,p = 0;

  g = field->nghost;
  for (i = 0; i < qnx; i ++)
  {
    for (j = 0; j < qny; j ++)
    {
      field->a[i+g][j+g] = buf[p++];
    }
  }
}
#endif

/*
 * Scatter AWSIM's Omegaz q-grid field. Unlike cell-centered state, wall-domain
 * q fields have an extra east/north line that is owned only by boundary ranks.
 */
static bool scatter_global_q_field (pawsim_field2d * field, real ** global_q,
                                    const pawsim_domain * dom)
{
#ifdef PAWSIM_USE_MPI
  int rank;
  uint qnx,qny;

  /*
   * q-grid ownership differs from cell ownership only at physical east/north
   * boundaries. Interior MPI edges do not duplicate the q line; they exchange
   * it through halos like any other derived field.
   */
  qnx = field->nx + q_extra_x(dom);
  qny = field->ny + q_extra_y(dom);

  if (dom->rank == 0)
  {
    copy_global_q_to_local(field,global_q,dom);

    for (rank = 1; rank < dom->size; rank ++)
    {
      int coords[2];
      uint i0,j0,nx,ny,rank_qnx,rank_qny;
      uint meta[2];
      real * buf = NULL;

      MPI_Cart_coords(dom->comm,rank,2,coords);
      i0 = block_start_local(dom->Nx,(uint) coords[0],(uint) dom->dims[0]);
      j0 = block_start_local(dom->Ny,(uint) coords[1],(uint) dom->dims[1]);
      nx = block_size_local(dom->Nx,(uint) coords[0],(uint) dom->dims[0]);
      ny = block_size_local(dom->Ny,(uint) coords[1],(uint) dom->dims[1]);
      rank_qnx = nx + (!dom->periodic_x && (i0+nx == dom->Nx) ? 1 : 0);
      rank_qny = ny + (!dom->periodic_y && (j0+ny == dom->Ny) ? 1 : 0);
      meta[0] = rank_qnx;
      meta[1] = rank_qny;
      buf = malloc((size_t) rank_qnx*rank_qny*sizeof(real));
      if (buf == NULL)
      {
        return false;
      }
      pack_global_q_tile(global_q,buf,i0,j0,rank_qnx,rank_qny);
      MPI_Send(meta,2,MPI_UNSIGNED,rank,210,dom->comm);
      MPI_Send(buf,(int) (rank_qnx*rank_qny),MPI_DOUBLE,rank,211,dom->comm);
      free(buf);
    }
  }
  else
  {
    uint meta[2];
    real * buf = NULL;

    MPI_Recv(meta,2,MPI_UNSIGNED,0,210,dom->comm,MPI_STATUS_IGNORE);
    if ((meta[0] != qnx) || (meta[1] != qny))
    {
      return false;
    }
    buf = malloc((size_t) qnx*qny*sizeof(real));
    if (buf == NULL)
    {
      return false;
    }
    MPI_Recv(buf,(int) (qnx*qny),MPI_DOUBLE,0,211,dom->comm,MPI_STATUS_IGNORE);
    unpack_local_q_tile(field,buf,qnx,qny);
    free(buf);
  }

  return true;
#else
  copy_global_q_to_local(field,global_q,dom);
  return true;
#endif
}

/** Read an optional 2-D AWSIM input and scatter it to the decomposed field. */
static bool read_and_scatter_2d (pawsim_field2d * field, const char * fname,
                                 const pawsim_config * cfg, const pawsim_domain * dom,
                                 FILE * errstrm)
{
  char path[MAX_PARAMETER_FILENAME_LENGTH];
  real ** global = NULL;
  bool ok = true;

  resolve_input_path(cfg,fname,path);
  if (strlen(path) == 0)
  {
    return true;
  }

  /** Missing optional files leave the field at its caller-supplied default. */
  if (dom->rank == 0)
  {
    global = matalloc(cfg->Nx,cfg->Ny);
    ok = (global != NULL) && readMatrix((char *) path,global,cfg->Nx,cfg->Ny,errstrm);
  }

#ifdef PAWSIM_USE_MPI
  {
    int ok_int = ok ? 1 : 0;
    MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
    ok = (ok_int != 0);
  }
#endif
  if (!ok)
  {
    if (global != NULL)
    {
      matfree(global);
    }
    return false;
  }

  ok = scatter_global_field(field,global,dom);
  if (global != NULL)
  {
    matfree(global);
  }
  return ok;
}

/** Read a required 2-D file by absolute path, used for restart/pickup fields. */
static bool read_and_scatter_2d_path (pawsim_field2d * field, const char * path,
                                      const pawsim_config * cfg, const pawsim_domain * dom,
                                      FILE * errstrm)
{
  real ** global = NULL;
  bool ok = true;

  if ((field == NULL) || (path == NULL) || (cfg == NULL) || (dom == NULL))
  {
    return false;
  }

  if (dom->rank == 0)
  {
    global = matalloc(cfg->Nx,cfg->Ny);
    ok = (global != NULL) && readMatrix((char *) path,global,cfg->Nx,cfg->Ny,errstrm);
  }

#ifdef PAWSIM_USE_MPI
  {
    int ok_int = ok ? 1 : 0;
    MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
    ok = (ok_int != 0);
  }
#endif
  if (!ok)
  {
    if (global != NULL)
    {
      matfree(global);
    }
    return false;
  }

  ok = scatter_global_field(field,global,dom);
  if (global != NULL)
  {
    matfree(global);
  }
  return ok;
}

/** Read and scatter Omegaz, stored by AWSIM on an (Nx+1) x (Ny+1) q grid. */
static bool read_and_scatter_q_omega (pawsim_field2d * field, const char * fname,
                                      const pawsim_config * cfg, const pawsim_domain * dom,
                                      FILE * errstrm)
{
  char path[MAX_PARAMETER_FILENAME_LENGTH];
  real ** global_q = NULL;
  bool ok = true;

  resolve_input_path(cfg,fname,path);
  if (strlen(path) == 0)
  {
    return true;
  }

  /** Omegaz.dat follows AWSIM's q-grid size, hence Nx+1 by Ny+1 on disk. */
  if (dom->rank == 0)
  {
    global_q = matalloc(cfg->Nx+1,cfg->Ny+1);
    ok = (global_q != NULL) && readMatrix(path,global_q,cfg->Nx+1,cfg->Ny+1,errstrm);
  }

#ifdef PAWSIM_USE_MPI
  {
    int ok_int = ok ? 1 : 0;
    MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
    ok = (ok_int != 0);
  }
#endif
  if (!ok)
  {
    if (global_q != NULL) matfree(global_q);
    return false;
  }

  ok = scatter_global_q_field(field,global_q,dom);
  if (global_q != NULL) matfree(global_q);
  return ok;
}

/** Read a layer-stacked AWSIM 3-D field and scatter each layer independently. */
static bool read_and_scatter_3d (pawsim_field2d * fields, const char * fname,
                                 const pawsim_config * cfg, const pawsim_domain * dom,
                                 FILE * errstrm)
{
  char path[MAX_PARAMETER_FILENAME_LENGTH];
  real *** global = NULL;
  uint k;
  bool ok = true;

  resolve_input_path(cfg,fname,path);
  if (strlen(path) == 0)
  {
    return true;
  }

  if (dom->rank == 0)
  {
    global = matalloc3(cfg->Nlay,cfg->Nx,cfg->Ny);
    ok = (global != NULL) && readMatrix3(path,global,cfg->Nlay,cfg->Nx,cfg->Ny,errstrm);
  }

#ifdef PAWSIM_USE_MPI
  {
    int ok_int = ok ? 1 : 0;
    MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
    ok = (ok_int != 0);
  }
#endif
  if (!ok)
  {
    if (global != NULL)
    {
      matfree3(global);
    }
    return false;
  }

  for (k = 0; k < cfg->Nlay; k ++)
  {
    real ** layer = (global == NULL) ? NULL : global[k];
    if (!scatter_global_field(&fields[k],layer,dom))
    {
      ok = false;
      break;
    }
  }

  if (global != NULL)
  {
    matfree3(global);
  }
  return ok;
}

/** Read a length-Nlay vector on rank 0 and broadcast it to all ranks. */
static bool read_and_broadcast_vector (real * vec, const char * fname,
                                       const pawsim_config * cfg,
                                       const pawsim_domain * dom,
                                       FILE * errstrm)
{
  char path[MAX_PARAMETER_FILENAME_LENGTH];
  bool ok = true;

  resolve_input_path(cfg,fname,path);
  if (strlen(path) != 0)
  {
    if (dom->rank == 0)
    {
      ok = readVector(path,vec,cfg->Nlay,errstrm);
    }

#ifdef PAWSIM_USE_MPI
    {
      int ok_int = ok ? 1 : 0;
      MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
      ok = (ok_int != 0);
    }
#endif
    if (!ok)
    {
      return false;
    }
  }

#ifdef PAWSIM_USE_MPI
  MPI_Bcast(vec,(int) cfg->Nlay,MPI_DOUBLE,0,dom->comm);
#endif
  return true;
}

/*
 * Allocate all state arrays needed by the currently parsed setup, including
 * optional forcing/restoring buffers. Arrays exist even when a feature is off
 * so later tendency code can use simple guards around physics, not storage.
 */
bool pawsim_state_alloc (pawsim_state * state, const pawsim_config * cfg,
                         const pawsim_domain * dom)
{
  uint k;

  if ((state == NULL) || (cfg == NULL) || (dom == NULL))
  {
    return false;
  }

  memset(state,0,sizeof(*state));
  state->Nlay = cfg->Nlay;
  state->tauNrecs = cfg->tauNrecs;
  state->wDiaNrecs = cfg->wDiaNrecs;
  /** Prognostic arrays are allocated per layer; wind records are per forcing time. */
  state->u = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->v = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->h = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->b = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->taux = calloc(cfg->tauNrecs,sizeof(pawsim_field2d));
  state->tauy = calloc(cfg->tauNrecs,sizeof(pawsim_field2d));
  state->uRelax = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->vRelax = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->hRelax = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->eRelax = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->bRelax = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->uTime = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->vTime = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->eTime = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->bTime = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->wdia_ff = calloc((size_t) cfg->wDiaNrecs*(cfg->Nlay+1),sizeof(pawsim_field2d));
  state->kappa_dia = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->nu_u_dia = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->nu_v_dia = calloc(cfg->Nlay,sizeof(pawsim_field2d));
  state->gg = calloc(cfg->Nlay,sizeof(real));
  state->geff = calloc(cfg->Nlay,sizeof(real));
  if ((state->u == NULL) || (state->v == NULL) || (state->h == NULL) || (state->b == NULL)
   || (state->taux == NULL) || (state->tauy == NULL)
   || (state->uRelax == NULL) || (state->vRelax == NULL)
   || (state->hRelax == NULL) || (state->eRelax == NULL) || (state->bRelax == NULL)
   || (state->uTime == NULL) || (state->vTime == NULL)
   || (state->eTime == NULL) || (state->bTime == NULL)
   || (state->wdia_ff == NULL) || (state->kappa_dia == NULL)
   || (state->nu_u_dia == NULL) || (state->nu_v_dia == NULL)
   || (state->gg == NULL) || (state->geff == NULL))
  {
    pawsim_state_free(state);
    return false;
  }

  for (k = 0; k < cfg->Nlay; k ++)
  {
    if (!pawsim_field2d_alloc(&state->u[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->v[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->h[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->b[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->uRelax[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->vRelax[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->hRelax[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->eRelax[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->bRelax[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->uTime[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->vTime[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->eTime[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->bTime[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->kappa_dia[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->nu_u_dia[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->nu_v_dia[k],dom->nx,dom->ny,dom->nghost))
    {
      pawsim_state_free(state);
      return false;
    }
  }

  for (k = 0; k < cfg->wDiaNrecs*(cfg->Nlay+1); k ++)
  {
    if (!pawsim_field2d_alloc(&state->wdia_ff[k],dom->nx,dom->ny,dom->nghost))
    {
      pawsim_state_free(state);
      return false;
    }
  }

  for (k = 0; k < cfg->tauNrecs; k ++)
  {
    if (!pawsim_field2d_alloc(&state->taux[k],dom->nx,dom->ny,dom->nghost)
     || !pawsim_field2d_alloc(&state->tauy[k],dom->nx,dom->ny,dom->nghost))
    {
      pawsim_state_free(state);
      return false;
    }
  }

  if (!pawsim_field2d_alloc(&state->hhb,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->hhs,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->omega_z,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->uLid,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->vLid,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->Fbaro_x,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->Fbaro_y,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->Fsurf_b,dom->nx,dom->ny,dom->nghost)
   || !pawsim_field2d_alloc(&state->hTime,dom->nx,dom->ny,dom->nghost))
  {
    pawsim_state_free(state);
    return false;
  }

  return true;
}

/** Free all state arrays; safe after partial allocation failure. */
void pawsim_state_free (pawsim_state * state)
{
  uint k;

  if (state == NULL)
  {
    return;
  }

  for (k = 0; k < state->Nlay; k ++)
  {
    pawsim_field2d_free(&state->u[k]);
    pawsim_field2d_free(&state->v[k]);
    pawsim_field2d_free(&state->h[k]);
    pawsim_field2d_free(&state->b[k]);
    pawsim_field2d_free(&state->uRelax[k]);
    pawsim_field2d_free(&state->vRelax[k]);
    pawsim_field2d_free(&state->hRelax[k]);
    pawsim_field2d_free(&state->eRelax[k]);
    pawsim_field2d_free(&state->bRelax[k]);
    pawsim_field2d_free(&state->uTime[k]);
    pawsim_field2d_free(&state->vTime[k]);
    pawsim_field2d_free(&state->eTime[k]);
    pawsim_field2d_free(&state->bTime[k]);
    pawsim_field2d_free(&state->kappa_dia[k]);
    pawsim_field2d_free(&state->nu_u_dia[k]);
    pawsim_field2d_free(&state->nu_v_dia[k]);
  }

  for (k = 0; k < state->wDiaNrecs*(state->Nlay+1); k ++)
  {
    pawsim_field2d_free(&state->wdia_ff[k]);
  }

  for (k = 0; k < state->tauNrecs; k ++)
  {
    pawsim_field2d_free(&state->taux[k]);
    pawsim_field2d_free(&state->tauy[k]);
  }

  free(state->u);
  free(state->v);
  free(state->h);
  free(state->b);
  free(state->taux);
  free(state->tauy);
  free(state->uRelax);
  free(state->vRelax);
  free(state->hRelax);
  free(state->eRelax);
  free(state->bRelax);
  free(state->uTime);
  free(state->vTime);
  free(state->eTime);
  free(state->bTime);
  free(state->wdia_ff);
  free(state->kappa_dia);
  free(state->nu_u_dia);
  free(state->nu_v_dia);
  free(state->gg);
  free(state->geff);
  pawsim_field2d_free(&state->hhb);
  pawsim_field2d_free(&state->hhs);
  pawsim_field2d_free(&state->omega_z);
  pawsim_field2d_free(&state->uLid);
  pawsim_field2d_free(&state->vLid);
  pawsim_field2d_free(&state->Fbaro_x);
  pawsim_field2d_free(&state->Fbaro_y);
  pawsim_field2d_free(&state->Fsurf_b);
  pawsim_field2d_free(&state->hTime);
  memset(state,0,sizeof(*state));
}

/** Read time-record-stacked 2-D forcing data such as taux/tauy. */
static bool read_and_scatter_record_fields (pawsim_field2d * fields, const char * fname,
                                            uint nrecs, const pawsim_config * cfg,
                                            const pawsim_domain * dom, FILE * errstrm)
{
  char path[MAX_PARAMETER_FILENAME_LENGTH];
  real *** global = NULL;
  uint n;
  bool ok = true;

  resolve_input_path(cfg,fname,path);
  if (strlen(path) == 0)
  {
    return true;
  }

  if (dom->rank == 0)
  {
    global = matalloc3(nrecs,cfg->Nx,cfg->Ny);
    ok = (global != NULL) && readMatrix3(path,global,nrecs,cfg->Nx,cfg->Ny,errstrm);
  }

#ifdef PAWSIM_USE_MPI
  {
    int ok_int = ok ? 1 : 0;
    MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
    ok = (ok_int != 0);
  }
#endif
  if (!ok)
  {
    if (global != NULL)
    {
      matfree3(global);
    }
    return false;
  }

  for (n = 0; n < nrecs; n ++)
  {
    real ** record = (global == NULL) ? NULL : global[n];
    if (!scatter_global_field(&fields[n],record,dom))
    {
      ok = false;
      break;
    }
  }

  if (global != NULL)
  {
    matfree3(global);
  }
  return ok;
}

/** Read time-record and interface-stacked diapycnal velocity fields. */
static bool read_and_scatter_interface_records (pawsim_field2d * fields,
                                                const char * fname,
                                                const pawsim_config * cfg,
                                                const pawsim_domain * dom,
                                                FILE * errstrm)
{
  char path[MAX_PARAMETER_FILENAME_LENGTH];
  real **** global = NULL;
  uint m,k;
  bool ok = true;

  resolve_input_path(cfg,fname,path);
  if (strlen(path) == 0)
  {
    return true;
  }

  if (dom->rank == 0)
  {
    global = matalloc4(cfg->wDiaNrecs,cfg->Nlay+1,cfg->Nx,cfg->Ny);
    ok = (global != NULL) && readMatrix4(path,global,cfg->wDiaNrecs,
                                         cfg->Nlay+1,cfg->Nx,cfg->Ny,errstrm);
  }

#ifdef PAWSIM_USE_MPI
  {
    int ok_int = ok ? 1 : 0;
    MPI_Bcast(&ok_int,1,MPI_INT,0,dom->comm);
    ok = (ok_int != 0);
  }
#endif
  if (!ok)
  {
    if (global != NULL)
    {
      matfree4(global);
    }
    return false;
  }

  for (m = 0; m < cfg->wDiaNrecs; m ++)
  {
    for (k = 0; k < cfg->Nlay+1; k ++)
    {
      real ** record = (global == NULL) ? NULL : global[m][k];
      if (!scatter_global_field(&fields[m*(cfg->Nlay+1)+k],record,dom))
      {
        ok = false;
        break;
      }
    }
    if (!ok)
    {
      break;
    }
  }

  if (global != NULL)
  {
    matfree4(global);
  }
  return ok;
}

/** Zero only U/V/H/B prognostic arrays, used for tendency buffers. */
void pawsim_state_zero_prognostic (pawsim_state * state)
{
  uint k;

  if (state == NULL)
  {
    return;
  }

  for (k = 0; k < state->Nlay; k ++)
  {
    pawsim_field2d_zero(&state->u[k]);
    pawsim_field2d_zero(&state->v[k]);
    pawsim_field2d_zero(&state->h[k]);
    pawsim_field2d_zero(&state->b[k]);
  }
}

/** Copy an entire local field allocation, including halos. */
static void copy_field_data (pawsim_field2d * dst, const pawsim_field2d * src)
{
  if ((dst == NULL) || (src == NULL) || (dst->data == NULL) || (src->data == NULL))
  {
    return;
  }

  memcpy(dst->data,src->data,(size_t) dst->sx*dst->sy*sizeof(real));
}

/** Copy all prognostic fields between state/tendency buffers. */
void pawsim_state_copy_prognostic (pawsim_state * dst, const pawsim_state * src)
{
  uint k;

  if ((dst == NULL) || (src == NULL))
  {
    return;
  }

  for (k = 0; k < dst->Nlay; k ++)
  {
    copy_field_data(&dst->u[k],&src->u[k]);
    copy_field_data(&dst->v[k],&src->v[k]);
    copy_field_data(&dst->h[k],&src->h[k]);
    copy_field_data(&dst->b[k],&src->b[k]);
  }
}

/** Exchange/fill halos for all prognostic fields using stagger-aware BCs. */
void pawsim_state_exchange_prognostic_halos (pawsim_state * state,
                                             const pawsim_domain * dom)
{
  uint k;

  if ((state == NULL) || (dom == NULL))
  {
    return;
  }

  /*
   * Use stagger-aware halo fills: u/v enforce wall-normal no-flow at their
   * respective wall faces, while h is scalar-reflected.
   */
  for (k = 0; k < state->Nlay; k ++)
  {
    pawsim_field2d_exchange_u_halo(&state->u[k],dom);
    pawsim_field2d_exchange_v_halo(&state->v[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->h[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->b[k],dom);
  }
}

/*
 * Initialize the model state from AWSIM setup files. Missing optional files
 * leave their fields at documented defaults; missing required active inputs
 * are caught by the relevant read call.
 */
bool pawsim_state_init (pawsim_state * state, const pawsim_config * cfg,
                        const pawsim_domain * dom, FILE * errstrm)
{
  uint k;

  if ((state == NULL) || (cfg == NULL) || (dom == NULL))
  {
    return false;
  }

  /** Defaults let simple test inputs omit optional files. */
  for (k = 0; k < state->Nlay; k ++)
  {
    fill_field(&state->u[k],0);
    fill_field(&state->v[k],0);
    fill_field(&state->h[k],0);
    fill_field(&state->b[k],0);
    fill_field(&state->uRelax[k],0);
    fill_field(&state->vRelax[k],0);
    fill_field(&state->hRelax[k],1000.0/state->Nlay);
    fill_field(&state->eRelax[k],1000.0*k/state->Nlay);
    fill_field(&state->bRelax[k],0);
    fill_field(&state->uTime[k],-1);
    fill_field(&state->vTime[k],-1);
    fill_field(&state->eTime[k],-1);
    fill_field(&state->bTime[k],-1);
    fill_field(&state->kappa_dia[k],0);
    fill_field(&state->nu_u_dia[k],0);
    fill_field(&state->nu_v_dia[k],0);
    state->gg[k] = 9.81;
    state->geff[k] = 0;
  }
  fill_field(&state->hhb,0);
  fill_field(&state->hhs,0);
  fill_field(&state->omega_z,0);
  fill_field(&state->uLid,0);
  fill_field(&state->vLid,0);
  fill_field(&state->Fbaro_x,0);
  fill_field(&state->Fbaro_y,0);
  fill_field(&state->Fsurf_b,0);
  fill_field(&state->hTime,-1);
  for (k = 0; k < state->tauNrecs; k ++)
  {
    fill_field(&state->taux[k],0);
    fill_field(&state->tauy[k],0);
  }
  for (k = 0; k < state->wDiaNrecs*(state->Nlay+1); k ++)
  {
    fill_field(&state->wdia_ff[k],0);
  }

  /*
   * Load AWSIM setup fields in the same broad order as the serial code:
   * static geometry, prognostic initial state, surface/body forcing,
   * restoring targets, diapycnal fields, and tracer-only inputs.
   */
  if (!read_and_scatter_2d(&state->hhs,cfg->hsFile,cfg,dom,errstrm)
   || !read_and_scatter_2d(&state->hhb,cfg->hbFile,cfg,dom,errstrm)
   || !read_and_scatter_q_omega(&state->omega_z,cfg->OmegazFile,cfg,dom,errstrm)
   || !read_and_broadcast_vector(state->gg,cfg->gFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->u,cfg->uInitFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->v,cfg->vInitFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->h,cfg->hInitFile,cfg,dom,errstrm)
   || (cfg->useTracer && !read_and_scatter_3d(state->b,cfg->bInitFile,cfg,dom,errstrm))
   || !read_and_scatter_record_fields(state->taux,cfg->tauxFile,cfg->tauNrecs,cfg,dom,errstrm)
   || !read_and_scatter_record_fields(state->tauy,cfg->tauyFile,cfg->tauNrecs,cfg,dom,errstrm)
   || !read_and_scatter_2d(&state->uLid,cfg->uLidFile,cfg,dom,errstrm)
   || !read_and_scatter_2d(&state->vLid,cfg->vLidFile,cfg,dom,errstrm)
   || !read_and_scatter_2d(&state->Fbaro_x,cfg->FbaroXFile,cfg,dom,errstrm)
   || !read_and_scatter_2d(&state->Fbaro_y,cfg->FbaroYFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->uRelax,cfg->uRelaxFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->vRelax,cfg->vRelaxFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->hRelax,cfg->hRelaxFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->eRelax,cfg->eRelaxFile,cfg,dom,errstrm)
   || (cfg->useTracer && !read_and_scatter_3d(state->bRelax,cfg->bRelaxFile,cfg,dom,errstrm))
   || !read_and_scatter_3d(state->uTime,cfg->uTimeFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->vTime,cfg->vTimeFile,cfg,dom,errstrm)
   || !read_and_scatter_2d(&state->hTime,cfg->hTimeFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->eTime,cfg->eTimeFile,cfg,dom,errstrm)
   || (cfg->useTracer && !read_and_scatter_3d(state->bTime,cfg->bTimeFile,cfg,dom,errstrm))
   || !read_and_scatter_interface_records(state->wdia_ff,cfg->wDiaFile,cfg,dom,errstrm)
   || (cfg->useTracer && !read_and_scatter_3d(state->kappa_dia,cfg->diaDiffFile,cfg,dom,errstrm))
   || (cfg->useTracer && !read_and_scatter_2d(&state->Fsurf_b,cfg->bFluxFile,cfg,dom,errstrm))
   || !read_and_scatter_3d(state->nu_u_dia,cfg->diaViscUFile,cfg,dom,errstrm)
   || !read_and_scatter_3d(state->nu_v_dia,cfg->diaViscVFile,cfg,dom,errstrm))
  {
    return false;
  }

  pawsim_state_exchange_prognostic_halos(state,dom);
  pawsim_field2d_exchange_scalar_halo(&state->hhb,dom);
  pawsim_field2d_exchange_scalar_halo(&state->hhs,dom);
  pawsim_field2d_exchange_q_halo(&state->omega_z,dom);
  pawsim_field2d_exchange_u_halo(&state->uLid,dom);
  pawsim_field2d_exchange_v_halo(&state->vLid,dom);
  pawsim_field2d_exchange_u_halo(&state->Fbaro_x,dom);
  pawsim_field2d_exchange_v_halo(&state->Fbaro_y,dom);
  for (k = 0; k < state->tauNrecs; k ++)
  {
    pawsim_field2d_exchange_scalar_halo(&state->taux[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->tauy[k],dom);
  }
  for (k = 0; k < state->wDiaNrecs*(state->Nlay+1); k ++)
  {
    pawsim_field2d_exchange_scalar_halo(&state->wdia_ff[k],dom);
  }
  for (k = 0; k < state->Nlay; k ++)
  {
    pawsim_field2d_exchange_u_halo(&state->uRelax[k],dom);
    pawsim_field2d_exchange_v_halo(&state->vRelax[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->hRelax[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->eRelax[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->bRelax[k],dom);
    pawsim_field2d_exchange_u_halo(&state->uTime[k],dom);
    pawsim_field2d_exchange_v_halo(&state->vTime[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->eTime[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->bTime[k],dom);
    pawsim_field2d_exchange_scalar_halo(&state->kappa_dia[k],dom);
    pawsim_field2d_exchange_u_halo(&state->nu_u_dia[k],dom);
    pawsim_field2d_exchange_v_halo(&state->nu_v_dia[k],dom);
  }
  pawsim_field2d_exchange_scalar_halo(&state->hTime,dom);
  pawsim_field2d_exchange_scalar_halo(&state->Fsurf_b,dom);

  /** geff is the cumulative reduced-gravity vector used by Bernoulli pressure. */
  state->geff[0] = state->gg[0];
  for (k = 1; k < state->Nlay; k ++)
  {
    state->geff[k] = state->geff[k-1] + state->gg[k];
  }
  for (k = 0; k < state->Nlay; k ++)
  {
    if (state->gg[k] < 0)
    {
      if (errstrm != NULL)
      {
        fprintf(errstrm,"ERROR: gFile may contain only non-negative values\n");
      }
      return false;
    }
  }

  return true;
}

/*
 * Overwrite prognostic variables from AWSIM/PAWSIM output files for a restart.
 * Static fields and forcing were already loaded from the setup file.
 */
bool pawsim_state_read_restart (pawsim_state * state, const pawsim_config * cfg,
                                const pawsim_domain * dom, const char * outdir,
                                uint startIdx, FILE * errstrm)
{
  uint k;
  char path[MAX_PARAMETER_FILENAME_LENGTH];

  if ((state == NULL) || (cfg == NULL) || (dom == NULL) || (outdir == NULL))
  {
    return false;
  }

  /*
   * AWSIM pickup files are ordinary model outputs. Static geometry and forcing
   * still come from the input directory, while U/V/H are overwritten from
   * outdir at the requested save index.
   */
  for (k = 0; k < cfg->Nlay; k ++)
  {
    snprintf(path,sizeof(path),"%s/U%u_n=%u.dat",outdir,k,startIdx);
    if (!read_and_scatter_2d_path(&state->u[k],path,cfg,dom,errstrm))
    {
      return false;
    }

    snprintf(path,sizeof(path),"%s/V%u_n=%u.dat",outdir,k,startIdx);
    if (!read_and_scatter_2d_path(&state->v[k],path,cfg,dom,errstrm))
    {
      return false;
    }

    snprintf(path,sizeof(path),"%s/H%u_n=%u.dat",outdir,k,startIdx);
    if (!read_and_scatter_2d_path(&state->h[k],path,cfg,dom,errstrm))
    {
      return false;
    }

    if (cfg->useTracer)
    {
      snprintf(path,sizeof(path),"%s/B%u_n=%u.dat",outdir,k,startIdx);
      if (!read_and_scatter_2d_path(&state->b[k],path,cfg,dom,errstrm))
      {
        return false;
      }
    }
  }

  pawsim_state_exchange_prognostic_halos(state,dom);
  return true;
}
