%%%
%%% createRunScript.m
%%%
%%% Convenience function to create an execution script for model runs.
%%%
%%% local_home_dir      Base directory path to hold experiment folder
%%% run_name            Name of experiment folder
%%% model_code_dir      Path to model source code files (on the machine on
%%%                     which the code will be compiled and executed)
%%% exec_name           Name of the compiled code executable
%%% use_intel           Set true to compile using intel compilers, false
%%%                     for gcc
%%% use_pbs             Set true to use grid engine to run the job on a
%%%                     remote cluster, false for regular execution
%%% use_cluster         Set true to create scripts to upload/download the
%%%                     experiment to/from a remote computing cluster
%%% uname               Username to log into the remote computing cluster
%%% cluster_addr        DNS address of the remote computing cluster
%%%                     Currently two options are supported as examples:
%%%                     1. caolila.atmos.ucla.edu
%%%                     2. hoffman2.idre.ucla.edu
%%%                     Add your own!
%%% cluster_home_dir    Base directory path to hold experiment folder on 
%%%                     the remote computing cluster
%%% use_mpi             Set true to run through MPI.
%%% mpi_nproc           Number of MPI ranks to request/use.
%%% mpi_launcher        Override the MPI launch command. If blank,
%%%                     use mpirun locally/SGE and srun under SLURM.
%%% mpi_nodes           Scheduler node count. Set 0 to leave this
%%%                     unspecified.
%%% mpi_tasks_per_node  Scheduler MPI tasks per node. Set 0 to leave this
%%%                     unspecified.
%%%
function createRunScript (  local_home_dir, ...
                            run_name, ...
                            model_code_dir, ...
                            exec_name, ...
                            use_intel, ...
                            use_pbs, ... 
                            use_cluster, ...
                            uname, ...
                            cluster_addr, ...
                            cluster_home_dir, ...
                            use_mpi, ...
                            mpi_nproc, ...
                            mpi_launcher, ...
                            mpi_nodes, ...
                            mpi_tasks_per_node)

  %%% Explicit MPI configuration. PAWSIM is a standalone package, so run-script
  %%% generation now requires all scheduler/MPI controls to be supplied by the
  %%% setup script rather than hidden in compatibility defaults.
  if (mpi_nproc > 1)
    use_mpi = true;
  end
  if (mpi_nproc < 1)
    error('mpi_nproc must be at least 1');
  end
  if (mpi_nodes < 0)
    error('mpi_nodes must be non-negative');
  end
  if (mpi_tasks_per_node < 0)
    error('mpi_tasks_per_node must be non-negative');
  end

  %%% File/directory names    
  local_run_dir = fullfile(local_home_dir,run_name);    
  sfname = fullfile(local_run_dir,'Run.sh');
  cleanfname = fullfile(local_run_dir,'Clean.sh');
  upfname = fullfile(local_run_dir,'Upload.sh');
  downfname = fullfile(local_run_dir,'Download.sh');  
  
  %%% Create a script file to run the code
  sfid = fopen(sfname,'w');
  if (sfid == -1)
    error(['Could not open ',sfname]);
  end

  %%% Copy code files over
  if (~copyfile(fullfile(model_code_dir,'/*'),local_run_dir))
    error(['Could not copy code files to ',local_run_dir]);
  end

  %%% To use intel compilers, need to add executables and libraries to system path
  if (use_intel)
    fprintf(sfid,'source /opt/intel/bin/compilervars.sh intel64\n');
  end

  %%% This line executes the C code. For MPI jobs, the scheduler scripts below
  %%% request mpi_nproc ranks and run with the scheduler-provided rank count
  %%% where possible.
  if (use_mpi)
    if (isempty(mpi_launcher))
      run_str = ['mpirun -np ',num2str(mpi_nproc),' ./',exec_name,' ',run_name,'_in ','. \n'];
    else
      run_str = [mpi_launcher,' ./',exec_name,' ',run_name,'_in ','. \n'];
    end
  else
    run_str = ['./',exec_name,' ',run_name,'_in ','. \n'];
  end
  
  %%% PBS submission requires a PBS script to be prepared
  if (use_pbs)
    
    pbsfid = fopen(fullfile(local_run_dir,'run_pawsim'),'w');
    if (pbsfid == -1)
      error(['Could not open ',fullfile(local_run_dir,'run_pawsim')]);
    end
    
    switch (cluster_addr)
      
      case 'caolila.atmos.ucla.edu'
      
        pbsstr = ...
        ['#!/bin/sh \n' ...
        '# \n' ...
        '# Your job name \n' ...
        '#$ -N ',run_name,' \n' ...
        '# \n' ...
        '# Use current working directory \n' ...
        '#$ -cwd \n' ...
        '# \n' ...
        '# Join stdout and stderr \n' ...
        '#$ -j y \n' ...
        '# \n' ...
        '# Exclude specific node \n' ...
        '#$ -l h=''!ardbeg3.atmos.ucla.edu'' \n' ...
        '# \n' ...
        '# Select queue to run on \n' ...
        '#$ -q Run.q \n' ...
        '# \n' ...
        '# pe request for MPI. Set your number of processors here. \n' ...
        '# Make sure you use the "impi" parallel environment. \n' ...
        '#$ -pe impi ',num2str(mpi_nproc),' \n' ...
        '# \n' ...
        '# Run job through bash shell \n' ...
        '#$ -S /bin/bash \n' ...
        '# \n' ...
        '## Output file \n' ...
        '#$ -o ./output.txt \n' ...
        '# \n' ...
        '\n'];

        fprintf(sfid,'qsub run_pawsim'); 
        if (use_mpi && isempty(mpi_launcher))
          run_str = ['mpirun -np ${NSLOTS:-',num2str(mpi_nproc),'} ./',exec_name,' ',run_name,'_in ','. \n'];
        end


      case 'lagavulin.atmos.ucla.edu'

        pbsstr = ...
          ['#!/bin/bash \n' ...
          '#  \n' ...
          '#SBATCH --job-name=',run_name,' \n' ...
          '#  \n' ...
          '# Use current working directory  \n' ...
          '#SBATCH --chdir=./  \n' ...
          '#  \n' ...
          '# Join stdout and stderr  \n' ...
          '#SBATCH -o output.txt  \n' ...
          '#SBATCH --error=output.txt  \n' ...
          '#  \n' ...
          '# Select queue  \n' ...
          '#SBATCH --partition=Run \n' ... 
          '# SBATCH -w ardbeg5          # select specific node  \n' ...           
          '#  \n' ...
          '# MPI task request. Set mpi_nproc in the setup script.  \n' ...
          '#SBATCH --ntasks=',num2str(mpi_nproc),'  \n' ...
          '#SBATCH --cpus-per-task=2         # Use 2 CPU per MPI rank because of Ardbeg/SLURM process accounting \n'];
        if (mpi_nodes > 0)
          pbsstr = [pbsstr, ...
          '#SBATCH --nodes=',num2str(mpi_nodes),'  \n'];
        end
        if (mpi_tasks_per_node > 0)
          pbsstr = [pbsstr, ...
          '#SBATCH --ntasks-per-node=',num2str(mpi_tasks_per_node),'  \n'];
        end
        pbsstr = [pbsstr, ...
          '#SBATCH --mem-per-cpu=1G          # Request memory per core (effectively 2G per process due to 2 CPUS per task above) \n' ...
          '# Output file  \n' ...
          '#SBATCH --output=output.txt  \n' ...
          '#  \n' ...
          '# Notify email address  \n' ...
          '#SBATCH --mail-user=sunnyyeh@atmos.ucla.edu  \n' ...
          '# notify me when  \n' ...
          '#SBATCH --mail-type=ALL  \n' ...
          '# \n' ...
          '# The following is for reporting only. It is not really needed  \n' ...
          '# to run the job. It will show up in your output file.  \n' ...
          '# echo "Got $SLURM_NPROCS processors."  \n' ...
          '# echo "Machines:"  \n' ...
          '# cat $TMPDIR/machines  \n' ...
          '#  \n' ...
          '# SLURM will set SLURM_NTASKS for MPI launch commands.  \n'];
        if (use_mpi && isempty(mpi_launcher))
          if (mpi_tasks_per_node > 0)
            hydra_ppn = mpi_tasks_per_node;
          else
            hydra_ppn = mpi_nproc;
          end
          pbsstr = [pbsstr, ...
            '# ========================================================== \n' ...
            '# 1. APPLY IT FIREWALL SPECS \n' ...
            '# ========================================================== \n' ...
            'export I_MPI_PORT_RANGE=60001:61000 \n' ...
            '\n' ...
            '# ========================================================== \n' ...
            '# 2. GENERATE A CLEAN, LOCAL NODE HOSTFILE \n' ...
            '# ========================================================== \n' ...
            '# This extracts the exact nodes Slurm assigned and formats them for Intel MPI. \n' ...
            'scontrol show hostnames $SLURM_JOB_NODELIST > intel_hosts.txt \n' ...
            '\n' ...
            '# ========================================================== \n' ...
            '# 3. FORCE BOOTSTRAP TO USE CLEAN SLURM RUNTIMES (NO NATIVE SSH) \n' ...
            '# ========================================================== \n' ...
            'export I_MPI_HYDRA_BOOTSTRAP=slurm \n' ...
            'export I_MPI_HYDRA_BOOTSTRAP_EXEC=srun \n' ...
            'export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=1 \n' ...
            '\n' ...
            '# Tell Intel MPI to pin ranks exclusively within Slurm’s allocated cgroup mask \n' ...
            'export I_MPI_PIN=1 \n' ...
            'export I_MPI_PIN_DOMAIN=mpicontrol \n'...
            '\n' ...
            '# Wipe out custom fabric settings to allow the runtime to auto-bridge. \n' ...
            'unset I_MPI_FABRICS \n' ...
            'unset FI_PROVIDER \n' ...
            '\n'];
        end

        fprintf(sfid,'sbatch run_pawsim'); 
        if (use_mpi && isempty(mpi_launcher))
          run_str = ...
            ['# ========================================================== \n' ...
            '# 4. EXECUTE VIA EXPLICIT HYDRA MANAGER WITH THE GENERATED HOSTFILE \n' ...
            '# ========================================================== \n' ...
            '# This avoids using srun as the direct MPI task launcher. \n' ...
            'mpiexec.hydra -f intel_hosts.txt -n ${SLURM_NTASKS:-',num2str(mpi_nproc),'} -ppn ',num2str(hydra_ppn),' ./',exec_name,' ',run_name,'_in ','. \n' ...
            '\n' ...
            '# Clean up hostfile after execution. \n' ...
            'rm -f intel_hosts.txt \n'];
        end

      case 'hoffman2.idre.ucla.edu'

        pbsstr = ...
        ['#!/bin/sh \n' ...
        '# Your job name \n' ...
        '#$ -N ',run_name,' \n' ...
        '# \n' ...
        '# Use current working directory \n' ...
        '#$ -cwd \n' ...
        '# \n' ...
        '# Join stdout and stderr \n' ...
        '#$ -j y \n' ...
        '# \n' ...
        '# \n' ...
        '# pe request for MPI. Set your number of processors here. \n' ...
        '#$ -pe dc* ',num2str(mpi_nproc),' \n' ...
        '# \n' ...
        '# Run job through bash shell \n' ...
        '#$ -S /bin/bash \n' ...
        '# \n' ...
        '## Output file \n' ...
        '#$ -o ./output.txt \n' ...
        '# \n' ...
        '# The following is for reporting only. It is not really needed \n' ...
        '# to run the job. It will show up in your output file. \n' ...
        '# echo "Got $num_proc processors." \n' ...
        '# echo "Machines:" \n' ...
        '# cat $TMPDIR/machines \n' ...
        '# \n' ...
        '# Use full pathname to make sure we are using the right mpirun \n' ...
        '# Gridengine will set NSLOTS and TMPDIR for you \n' ...        
        '#$ -m bea \n' ...
        '#$ -l h_data=1G,h_rt=24:00:00 \n' ...
        '# $ -l h_data=1G,h_rt=336:00:00,highp \n'];        

        if (use_mpi)          
          pbsstr = [pbsstr, ...
            '. /u/local/Modules/default/init/modules.sh \n' ...
            'module load intel/2020.4  \n' ...
            '\n'];
        end

        fprintf(sfid,'qsub run_pawsim'); 
        if (use_mpi && isempty(mpi_launcher))
          run_str = ['mpirun -np ${NSLOTS:-',num2str(mpi_nproc),'} ./',exec_name,' ',run_name,'_in ','. \n'];
        end

      otherwise

        fclose(pbsfid);
        error(['No scheduler template defined for ',cluster_addr]);

    end
  
    fprintf(pbsfid,pbsstr);
    fprintf(pbsfid,run_str);
    fclose(pbsfid);
    
      

  else
    
    fprintf(sfid,run_str);  
    
  end

  fclose(sfid);  
  
  %%% Create a file to clean the run folder of output files
  cleanstr = ['for f in ./*n=*.dat; do rm $f; done'];
  cleanfid = fopen(cleanfname,'w');
  if (cleanfid == -1)
    error(['Could not open ',cleanfname]);
  end
  fprintf(cleanfid,cleanstr);
  fclose(cleanfid);
  
  if (use_cluster)
    
    %%% Create a file to upload the run to the cluster    
    upstr = ['rsync -av --update ',fullfile('..',run_name),' ',uname,'@',cluster_addr,':',cluster_home_dir];
    upfid = fopen(upfname,'w');
    if (upfid == -1)
      error(['Could not open ',upfname]);
    end
    fprintf(upfid,'%s',upstr);
    fclose(upfid);
    
    %%% Create a file to download the run from the cluster
    downstr = ['rsync -av --update ',uname,'@',cluster_addr,':',cluster_home_dir,'/',run_name,' ../'];
    downfid = fopen(downfname,'w');
    if (downfid == -1)
      error(['Could not open ',downfname]);
    end
    fprintf(downfid,'%s',downstr);
    fclose(downfid);
    
  end

end
